# Generated by Django 3.2.8 on 2021-11-02 07:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, choices=[('b', 'Bread'), ('f', 'Fruit'), ('m', 'Meat'), ('g', 'Greens'), ('w', 'Water'), ('c', 'Caffine')], default='m', help_text='Kind of food', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='KindInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('x', 'full'), ('o', 'empty')], default='o', help_text='was this consumed?', max_length=1)),
                ('kind', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.kind')),
            ],
        ),
        migrations.AlterField(
            model_name='food',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.kind'),
        ),
    ]
