# Generated by Django 3.2.9 on 2021-11-03 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0005_auto_20211102_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bread', models.IntegerField(blank=True, null=True, verbose_name='Total of bread')),
                ('total_fruit', models.IntegerField(blank=True, null=True, verbose_name='Total of fruit')),
                ('total_meat', models.IntegerField(blank=True, null=True, verbose_name='Total of meat')),
                ('total_greens', models.IntegerField(blank=True, null=True, verbose_name='Total of greens')),
                ('total_water', models.IntegerField(blank=True, null=True, verbose_name='Total of water')),
                ('total_caffeine', models.IntegerField(blank=True, null=True, verbose_name='Total of caffeine')),
                ('total_potassium', models.IntegerField(blank=True, null=True, verbose_name='Total of potassium')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_bread', models.IntegerField(blank=True, null=True, verbose_name='Total of bread')),
                ('max_fruit', models.IntegerField(blank=True, null=True, verbose_name='Total of fruit')),
                ('max_meat', models.IntegerField(blank=True, null=True, verbose_name='Total of meat')),
                ('max_greens', models.IntegerField(blank=True, null=True, verbose_name='Total of greens')),
                ('max_water', models.IntegerField(blank=True, null=True, verbose_name='Total of water')),
                ('max_caffeine', models.IntegerField(blank=True, null=True, verbose_name='Total of caffeine')),
                ('max_potassium', models.IntegerField(blank=True, null=True, verbose_name='Total of potassium')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
