# Generated by Django 3.2.9 on 2021-11-03 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_day_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
