# Generated by Django 3.2.9 on 2021-11-04 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0007_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this tool across whole collection', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('x', 'Eaten'), ('o', 'Not Eaten')], default='m', help_text='Was it eaten', max_length=1)),
                ('eater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.food')),
            ],
        ),
    ]
