# Generated by Django 3.2.9 on 2021-11-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20211106_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_bread', models.IntegerField(blank=True, null=True, verbose_name='Total of bread')),
                ('max_fruit', models.IntegerField(blank=True, null=True, verbose_name='Total of fruit')),
                ('max_meat', models.IntegerField(blank=True, null=True, verbose_name='Total of meat')),
                ('max_greens', models.IntegerField(blank=True, null=True, verbose_name='Total of greens')),
                ('max_water', models.IntegerField(blank=True, null=True, verbose_name='Total of water')),
                ('max_caffeine', models.IntegerField(blank=True, null=True, verbose_name='Total of caffeine')),
                ('max_potassium', models.IntegerField(blank=True, null=True, verbose_name='Total of potassium')),
                ('max_calories', models.IntegerField(blank=True, null=True, verbose_name='Total of calories')),
            ],
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
