# Generated by Django 3.2.9 on 2021-11-08 05:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20211106_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
