# Generated by Django 3.2.9 on 2021-11-08 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_food_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodinstance',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
