# Generated by Django 3.2.9 on 2021-11-08 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_foodinstance_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodinstance',
            old_name='created',
            new_name='consumed',
        ),
        migrations.RemoveField(
            model_name='food',
            name='status',
        ),
    ]
