# Generated by Django 3.2.9 on 2021-12-10 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0015_alter_foodinstance_eater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodinstance',
            name='eater',
            field=models.ForeignKey(blank=True, default='me', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
