# Generated by Django 3.2.9 on 2021-12-11 06:32

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0019_alter_foodinstance_eater'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this food instance across whole collection', primary_key=True, serialize=False)),
                ('consumed', models.DateTimeField(auto_now_add=True)),
                ('eater', models.ForeignKey(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(default='Pellegrino', null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.food')),
            ],
        ),
    ]
