# Generated by Django 3.2.9 on 2021-12-11 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_waterinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterinstance',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.food'),
        ),
    ]
