# Generated by Django 3.2.9 on 2021-12-11 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_waterinstance_food'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaterInstance',
        ),
    ]
