# Generated by Django 3.2.9 on 2021-12-17 06:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_delete_waterinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodinstance',
            name='food',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.food'),
        ),
        migrations.AlterField(
            model_name='foodinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID across whole collection', primary_key=True, serialize=False),
        ),
    ]
