# Generated by Django 3.2.9 on 2021-12-17 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20211216_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodinstance',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.food'),
        ),
    ]
