# Generated by Django 3.2.9 on 2021-12-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_alter_foodinstance_eater'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='oil',
            field=models.IntegerField(blank=True, null=True, verbose_name='Amount of oil'),
        ),
    ]
