# Generated by Django 3.2.9 on 2021-12-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_daily_intake_max_oil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_intake',
            name='max_calories',
        ),
        migrations.RemoveField(
            model_name='food',
            name='calories',
        ),
        migrations.AddField(
            model_name='daily_intake',
            name='max_carbs',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total of carbs'),
        ),
        migrations.AddField(
            model_name='daily_intake',
            name='max_magnesium',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total of magnesium'),
        ),
        migrations.AddField(
            model_name='daily_intake',
            name='max_protein',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total of protein'),
        ),
        migrations.AddField(
            model_name='food',
            name='carbs',
            field=models.IntegerField(blank=True, null=True, verbose_name='Amount of carbs'),
        ),
        migrations.AddField(
            model_name='food',
            name='magnesium',
            field=models.IntegerField(blank=True, null=True, verbose_name='Amount of magnesium'),
        ),
        migrations.AddField(
            model_name='food',
            name='protein',
            field=models.IntegerField(blank=True, null=True, verbose_name='Amount of protein'),
        ),
        migrations.AlterField(
            model_name='food',
            name='kind',
            field=models.CharField(blank=True, choices=[('b', 'Bread'), ('f', 'Fruit'), ('m', 'Meat'), ('g', 'Greens'), ('w', 'Water'), ('c', 'Caffeine'), ('o', 'Oil'), ('s', 'Snacks')], default='m', max_length=1),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
