# Generated by Django 3.2.9 on 2021-12-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_auto_20211220_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_intake',
            name='max_calories',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total of calories'),
        ),
        migrations.AddField(
            model_name='food',
            name='calories',
            field=models.IntegerField(blank=True, null=True, verbose_name='Amount of calories'),
        ),
    ]
