# Generated by Django 3.2.9 on 2021-12-28 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_auto_20211220_2321'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Daily_Intake',
            new_name='DailyIntake',
        ),
    ]
