# Generated by Django 3.2.9 on 2021-12-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_rename_daily_intake_dailyintake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyintake',
            name='max_carbs',
        ),
        migrations.RemoveField(
            model_name='food',
            name='carbs',
        ),
        migrations.AddField(
            model_name='dailyintake',
            name='max_fat',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total of fat'),
        ),
        migrations.AddField(
            model_name='dailyintake',
            name='max_iron',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total of iron'),
        ),
        migrations.AddField(
            model_name='food',
            name='fat',
            field=models.IntegerField(blank=True, null=True, verbose_name='Amount of fat'),
        ),
        migrations.AddField(
            model_name='food',
            name='iron',
            field=models.IntegerField(blank=True, null=True, verbose_name='Amount of iron'),
        ),
    ]
