# Generated by Django 3.2.9 on 2021-12-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_auto_20211228_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='kind',
            field=models.CharField(blank=True, choices=[('b', 'Bread'), ('f', 'Fruit'), ('m', 'Meat'), ('g', 'Greens'), ('w', 'Water'), ('c', 'Caffeine'), ('o', 'Oil'), ('x', 'Extra')], default='m', max_length=1),
        ),
    ]
