# Generated by Django 3.2.9 on 2021-12-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_auto_20211229_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='oil',
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Amount of fat'),
        ),
        migrations.AlterField(
            model_name='food',
            name='iron',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Amount of iron'),
        ),
        migrations.AlterField(
            model_name='food',
            name='magnesium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Amount of magnesium'),
        ),
        migrations.AlterField(
            model_name='food',
            name='potassium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Amount of potassium'),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Amount of protein'),
        ),
    ]
